### ISSUE TITLE
Where to put the parameters

### ISSUE THREAD

**Issue by jay3ss** [zkytony/ROSNavigationGuide#1]
Great write up and thanks for publishing this for everyone to use. I'm having some trouble figuring out exactly how to use many of the parameters discussed in the guide and I think that a quick example for these would be beneficial and also save time.

For example, I am reading 3.1.3 DWA Local Planner : Trajactory Scoring [sic], and in that section you discuss the `cost` and how it is calculated using the `path_distance_bias`, `goal_distance_bias`, and `occdist_scale` parameters. Where exactly do these go? 

Let's say I'm following the [Robot Setup portion of the ROS navigation tutorials](http://wiki.ros.org/navigation/Tutorials/RobotSetup). In the tutorial, I am given example parameter files and an example launch file. Would these parameters be set in the `base_local_planner_params.yaml` file? For example:

```
TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  ...

  dwa: true
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
```

Little details like this would, IMHO, make an already great resource just that much better. As great as the ROS wiki is, it is sometimes lacking and I find resources like this one to be a huge help to me.

**Comment by zkytony** [comment]
Thank you so much for reading the guide! I'm glad you find it helpful!

Regarding your question, be careful. There is a `base_local_planner` package ([link](http://wiki.ros.org/base_local_planner)) and a `dwa_local_planner` package ([link](http://wiki.ros.org/dwa_local_planner)). On the guide, I discuss the latter. Parameter names such as `path_distance_bias` appear in the `dwa_local_planner`. But for `base_local_planner`, their names & default values are different (e.g. `path_distance_bias` is called `pdist_scale`). 

I suggest your to directly use `dwa_local_planner`. So your parameters file (in yaml format) goes like:
```
DWAPlannerROS:

   max_vel_x: 0.45
   min_vel_x: 0.1

    ...

   path_distance_bias: 32.0
   goal_distance_bias: 20.0
   occdist_scale: 0.02
``` 

There are two tools that I hope you've already been using when tuning your robot's navigation behavior. First, use RVIZ ([link](http://wiki.ros.org/rviz)) to visualize the navigation planning & execution. Second, use rqt reconfigure as follows to view the parameter names and dynamically configure the parameters.
```
rosrun rqt_reconfigure rqt_reconfigure
```

The guide assumes that the reader has set up the navigation stack and ready to fine-tune it. I agree that providing details would help, and I welcome contributions in this respect. But I'm currently focused on other research projects, so it is not my top priority at the moment. Hope you understand!
